name: google_books_api
description: A library to help on the search for books on google books api
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  http: ^0.13.5
  equatable: ^2.0.5
  json_annotation: ^4.7.0

dev_dependencies:
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  test: ^1.22.0
  very_good_analysis: ^3.1.0
