name: google_books_api
description: A library to help on the search for books on google books api
version: 1.0.1
repository: https://github.com/GiudaBallerino/google_books_api

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  http: ^1.2.2
  equatable: ^2.0.5
  json_annotation: ^4.9.0

dev_dependencies:
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  test: ^1.25.8
  very_good_analysis: ^6.0.0
